version: "3"

services:
  webserver:
    build:
        context: ./www
    ports:
       - "80:80"
    environment:
     - APACHE_RUN_USER=#1000
     - TERM=xterm-256color
    links: 
      - redis
      - mysql
    volumes: 
      - ./www:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/vhosts:/etc/apache2/sites-enabled
      - ./logs/apache2:/var/log/apache2
      - ./config/ssl:/var/ssl
  mysql:
    image: mysql:8.0.18
    links:
      - redis
    environment:
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_DATABASE: data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - redis
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8081:80'
    volumes: 
      - /sessions
  redis:
    image: redis
    command: redis-server --requirepass 1234
    environment:
    - ALLOW_EMPTY_PASSWORD=yes
    - REDIS_PASSWORD=1234

