version: "3"
services:
  webserver:
    build:
        context: .
    ports:
       - "85:80"
    environment:
     - APACHE_RUN_USER=#1000
     - TERM=xterm-256color
    links: 
      - redis
      - mysql
    volumes: 
      - .:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./default.conf:/etc/apache2/sites-enabled/default.conf
  mysql:
    image: mysql:8.0.18
    links:
      - redis
    environment:
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_DATABASE: data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - redis
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8081:80'
    volumes: 
      - /sessions
  redis:
    image: redis
    command: redis-server --requirepass 1234
    environment:
    - ALLOW_EMPTY_PASSWORD=yes
    - REDIS_PASSWORD=1234

