version: '2'

services:
   db:
     build: ./mysql
     volumes:
       - ./mysql/db_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: root
   php:
    build: ./php
    ports:
      - '80:80'
      - '443:443'
    restart: always
    volumes:
       - ./php/var:/var/log/apache2
       - ./html:/var/www/html
       - ./apache2:/etc/apache2
    depends_on:
      - db
volumes:
    db_data:
